micronaut:
  application:
    name: ServiceWeather
  router:
    static-resources:
      main:
        paths: classpath:views
        mapping: /weather/**

datasources:
  default:
    url: jdbc:mysql://weather_db:3306/weatherdb?serverTimezone=Europe/Berlin
#    url: jdbc:mysql://localhost:3306/weatherdb?serverTimezone=Europe/Berlin
    driverClassName: com.mysql.cj.jdbc.Driver
    username: weatherdb
    password: 'Control!123'

jpa:
  default:
    entity-scan:
      packages: de.malosoft.weather.svc
    properties:
      hibernate:
        hbm2ddl: 
          auto: update
        show_sql: true
